### ISSUE TITLE
I need the diagram-PDF file of the book.

### ISSUE THREAD

**Issue by abysslover** [PacktPublishing/Hands-on-Artificial-Intelligence-with-TensorFlow-Book#3]
Dear Mr. Ziai (@ankitdx), and @Packt-ITService,

The link to the [PDF file](https://github.com/PacktPublishing/Hands-on-Artificial-Intelligence-with-TensorFlow-Book/blob/master) seems to be broken. I would appreciate it if you could upload the PDF file again.
  I am preparing for a short AI course using this book as a textbook. Thus, the PDF file would be very helpful to shorten time to prepare lecture notes and presentations.

Thanks in advance.

**Comment by shubham763** [comment]
Hi @abysslover 

We have uploaded the pdf and updated the readme as well.
https://static.packt-cdn.com/downloads/9781788998079_ColorImages.pdf
you can use the above link or you can get the link from GitHub readme
